### ISSUE TITLE
Improve sharing of configurations

### ISSUE THREAD

**Issue by doki-nordic** [doki-nordic/docker-files#1]
* Allow configuration assigned to docker file, e.g. `./example.yaml` will be assigned to `./example.Dockerfile`.
  * Configuration will be merged, options from main config file will override docker config.
* Allow parameters in configuration, e.g. docker config has `mem_limit: $$${MEM_LIMIT}` and parameter `params.MEM_LIMIT` with default value `"4g"`.\
  * It can be done using jinja
  * The parameters will be available in configuration, pre/post-build scripts, and dockerfile
  * Parameters can be done using `prompt` (maybe renamed to `input`), e.g. in dockerfile config:
    ```yaml
    prompt:
      MEM_LIMIT: Memory limit  # Create parameter
    set:
      MEM_LIMIT: 4g  # Set default value
    ```
    In global config:
    ```yaml
    set:
      MEM_LIMIT: 1g  # Override default value
    ```
